version: '2'

# same as 
# docker run -p 8088:80 -v html:/usr/local/apache2/htdocs/ httpd

services:
  web:
    image: httpd
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - '8088:80'


